PackageIdentifier: ProtagonistLabs.BackupLabs
PackageVersion: 1.0.4
InstallerType: inno
Scope: user
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/backup-labs/releases/download/v1.0.4/BackupLabs-1.0.4-setup.exe
  InstallerSha256: 8BA6AE78F7214B3E6F60381E0F31E8DF4E1935FC98CEB346C7975803F9D59F44
ManifestType: installer
ManifestVersion: 1.6.0
