PackageIdentifier: ProtagonistLabs.AutoClicker
PackageVersion: 1.0.6
InstallerType: portable
Commands:
- autoclicker
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/auto-clicker/releases/download/v1.0.6/Auto.Clicker.exe
  InstallerSha256: 1E6B27FD58DDF87CB214EC9B4D7B33E965842A206BADB25F6AD6435F74DD3F8B
ManifestType: installer
ManifestVersion: 1.6.0
