PackageIdentifier: ProtagonistLabs.CursorSelector
PackageVersion: 1.0.2
InstallerType: portable
Commands:
- cursorselector
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/cursor-selector/releases/download/v1.0.2/CursorSelector.exe
  InstallerSha256: E9A1E31858D9BC80E2602D7E041DAE989CDF1D9ACF324457289ECC83573AA0D5
ManifestType: installer
ManifestVersion: 1.6.0
