PackageIdentifier: ProtagonistLabs.CursorSelector
PackageVersion: 1.0.1
InstallerType: portable
Commands:
- cursorselector
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/cursor-selector/releases/download/v1.0.1/CursorSelector.exe
  InstallerSha256: 49ACBCE045BC6D69D8DA9928E8AD9F7F55C9A40916043456FC5D8BE829E2BD20
ManifestType: installer
ManifestVersion: 1.6.0
