PackageIdentifier: ProtagonistLabs.SteamRadar
PackageVersion: 0.4.2
InstallerType: portable
Commands:
- steamradar
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/steamradar/releases/download/v0.4.2/SteamRadar-0.4.2-portabil.exe
  InstallerSha256: 93B7A73AA25B7047C1A028D09F72FA68D344BB3BF4051FF815ABBD28EECA2418
ManifestType: installer
ManifestVersion: 1.6.0
