PackageIdentifier: ProtagonistLabs.Sysoptimizer
PackageVersion: 1.4.0
InstallerType: portable
Commands:
- sysoptimizer
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/sysoptimizer/releases/download/v1.4.0/Sysoptimizer.exe
  InstallerSha256: DD0DE2A677D8A741DE287B10DA2EB62A188C41E99C67A54589B824D985E319EB
ManifestType: installer
ManifestVersion: 1.6.0
