PackageIdentifier: ProtagonistLabs.SteamRadar
PackageVersion: 0.4.3
InstallerType: portable
Commands:
- steamradar
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/steamradar/releases/download/v0.4.3/SteamRadar-0.4.3-portabil.exe
  InstallerSha256: E1E35B8B5257B3DFAE9500354A5CE88CF29DB7485CCD86F47E5ADE0AF9C58BE5
ManifestType: installer
ManifestVersion: 1.6.0
