PackageIdentifier: ProtagonistLabs.AutoClicker
PackageVersion: 1.0.7
InstallerType: portable
Commands:
- autoclicker
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/auto-clicker/releases/download/v1.0.7/Auto.Clicker.exe
  InstallerSha256: AF06268C2286F19CE297785C7D4DC744151EFCA75F879BF2FC8E9BA14DC8D4AB
ManifestType: installer
ManifestVersion: 1.6.0
