PackageIdentifier: ProtagonistLabs.Sysoptimizer
PackageVersion: 1.4.1
InstallerType: portable
Commands:
- sysoptimizer
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/sysoptimizer/releases/download/v1.4.1/Sysoptimizer.exe
  InstallerSha256: 7D3527FBB9E90F28F23ED83AD6A53B6C13B7211A35434CDB366FDEEA4862CFA4
ManifestType: installer
ManifestVersion: 1.6.0
