PackageIdentifier: ProtagonistLabs.CursorSelector
PackageVersion: 1.1.0
InstallerType: portable
Commands:
- cursorselector
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/cursor-selector/releases/download/v1.1.0/CursorSelector.exe
  InstallerSha256: 99AB2C23D638B45852C3D4675755DD03B1526EE00D43F00D9C782D5E80960E3E
ManifestType: installer
ManifestVersion: 1.6.0
