PackageIdentifier: ProtagonistLabs.SteamRadar
PackageVersion: 0.6.0
InstallerType: portable
Commands:
- steamradar
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/steamradar/releases/download/v0.6.0/SteamRadar-0.6.0-portabil.exe
  InstallerSha256: 2B770DC47B9EA2E5550CB81FDC8A8761F47B5C0AADB3947F393681D6F43A319D
ManifestType: installer
ManifestVersion: 1.6.0
