PackageIdentifier: ProtagonistLabs.Lume
PackageVersion: 0.1.10
InstallerType: nullsoft
Scope: user
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/lume/releases/download/v0.1.10/Lume-0.1.10-x64.exe
  InstallerSha256: 862A7C36296E37CBFC4519A016AFEDE54F40643E46399D3528321AA9559870AE
ManifestType: installer
ManifestVersion: 1.6.0
