PackageIdentifier: ProtagonistLabs.Glaze
PackageVersion: 2.0.5
InstallerType: inno
Scope: user
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/glaze/releases/download/v2.0.5/Glaze-Setup-2.0.5.exe
  InstallerSha256: 7E51FAE72DFC0E4F874EC5E2E60296B739D802E8B992DD55F44F0C7CB418FC80
ManifestType: installer
ManifestVersion: 1.6.0

